name: deploy-marketing
on:
  push:
    branches:
      - master
    paths:
      - 'packages/marketing/**'
defaults:
  run:
    working-directory: packages/marketing

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Building App
        run: npm run build
      - name: Vercel Action
        uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.MARKETING_PROJECT_ID}} #Required 